### 회원가입

POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "artinfo",
  "email": "artinfokorea20222@gmail.com",
  "password": "a123456!"
}

### 로그인

POST http://localhost:8080/auth/login/email
Content-Type: application/json

{
  "email": "artinfokorea20222@gmail.com",
  "password": "a123456!"
}

### 유저 페이지
